// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: order.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderCreateReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderNo        string                 `protobuf:"bytes,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	UserID         uint64                 `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	OrderStatus    int64                  `protobuf:"varint,4,opt,name=orderStatus,proto3" json:"orderStatus,omitempty"`
	PaymentStatus  int64                  `protobuf:"varint,5,opt,name=paymentStatus,proto3" json:"paymentStatus,omitempty"`
	TotalAmount    int64                  `protobuf:"varint,6,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	PaidAmount     int64                  `protobuf:"varint,7,opt,name=paidAmount,proto3" json:"paidAmount,omitempty"`
	ConsigneeName  string                 `protobuf:"bytes,8,opt,name=consigneeName,proto3" json:"consigneeName,omitempty"`
	ConsigneePhone string                 `protobuf:"bytes,9,opt,name=consigneePhone,proto3" json:"consigneePhone,omitempty"`
	Address        string                 `protobuf:"bytes,10,opt,name=address,proto3" json:"address,omitempty"`
	Remark         string                 `protobuf:"bytes,11,opt,name=remark,proto3" json:"remark,omitempty"`
	ShipmentNo     string                 `protobuf:"bytes,12,opt,name=shipmentNo,proto3" json:"shipmentNo,omitempty"`
	ExpressName    string                 `protobuf:"bytes,13,opt,name=expressName,proto3" json:"expressName,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderCreateReq) Reset() {
	*x = OrderCreateReq{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreateReq) ProtoMessage() {}

func (x *OrderCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreateReq.ProtoReflect.Descriptor instead.
func (*OrderCreateReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderCreateReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderCreateReq) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *OrderCreateReq) GetOrderStatus() int64 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *OrderCreateReq) GetPaymentStatus() int64 {
	if x != nil {
		return x.PaymentStatus
	}
	return 0
}

func (x *OrderCreateReq) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *OrderCreateReq) GetPaidAmount() int64 {
	if x != nil {
		return x.PaidAmount
	}
	return 0
}

func (x *OrderCreateReq) GetConsigneeName() string {
	if x != nil {
		return x.ConsigneeName
	}
	return ""
}

func (x *OrderCreateReq) GetConsigneePhone() string {
	if x != nil {
		return x.ConsigneePhone
	}
	return ""
}

func (x *OrderCreateReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OrderCreateReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *OrderCreateReq) GetShipmentNo() string {
	if x != nil {
		return x.ShipmentNo
	}
	return ""
}

func (x *OrderCreateReq) GetExpressName() string {
	if x != nil {
		return x.ExpressName
	}
	return ""
}

type OrderCreateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreateResp) Reset() {
	*x = OrderCreateResp{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreateResp) ProtoMessage() {}

func (x *OrderCreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreateResp.ProtoReflect.Descriptor instead.
func (*OrderCreateResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderCreateResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OrderCreateResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type OrderDelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDelReq) Reset() {
	*x = OrderDelReq{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDelReq) ProtoMessage() {}

func (x *OrderDelReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDelReq.ProtoReflect.Descriptor instead.
func (*OrderDelReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *OrderDelReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type OrderDelResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDelResp) Reset() {
	*x = OrderDelResp{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDelResp) ProtoMessage() {}

func (x *OrderDelResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDelResp.ProtoReflect.Descriptor instead.
func (*OrderDelResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *OrderDelResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OrderDelResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type OrderUpdateReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderNo        string                 `protobuf:"bytes,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	UserID         uint64                 `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	OrderStatus    int64                  `protobuf:"varint,4,opt,name=orderStatus,proto3" json:"orderStatus,omitempty"`
	PaymentStatus  int64                  `protobuf:"varint,5,opt,name=paymentStatus,proto3" json:"paymentStatus,omitempty"`
	TotalAmount    int64                  `protobuf:"varint,6,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	PaidAmount     int64                  `protobuf:"varint,7,opt,name=paidAmount,proto3" json:"paidAmount,omitempty"`
	ConsigneeName  string                 `protobuf:"bytes,8,opt,name=consigneeName,proto3" json:"consigneeName,omitempty"`
	ConsigneePhone string                 `protobuf:"bytes,9,opt,name=consigneePhone,proto3" json:"consigneePhone,omitempty"`
	Address        string                 `protobuf:"bytes,10,opt,name=address,proto3" json:"address,omitempty"`
	Remark         string                 `protobuf:"bytes,11,opt,name=remark,proto3" json:"remark,omitempty"`
	ShipmentNo     string                 `protobuf:"bytes,12,opt,name=shipmentNo,proto3" json:"shipmentNo,omitempty"`
	ExpressName    string                 `protobuf:"bytes,13,opt,name=expressName,proto3" json:"expressName,omitempty"`
	Id             int64                  `protobuf:"varint,14,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderUpdateReq) Reset() {
	*x = OrderUpdateReq{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderUpdateReq) ProtoMessage() {}

func (x *OrderUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderUpdateReq.ProtoReflect.Descriptor instead.
func (*OrderUpdateReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *OrderUpdateReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderUpdateReq) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *OrderUpdateReq) GetOrderStatus() int64 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *OrderUpdateReq) GetPaymentStatus() int64 {
	if x != nil {
		return x.PaymentStatus
	}
	return 0
}

func (x *OrderUpdateReq) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *OrderUpdateReq) GetPaidAmount() int64 {
	if x != nil {
		return x.PaidAmount
	}
	return 0
}

func (x *OrderUpdateReq) GetConsigneeName() string {
	if x != nil {
		return x.ConsigneeName
	}
	return ""
}

func (x *OrderUpdateReq) GetConsigneePhone() string {
	if x != nil {
		return x.ConsigneePhone
	}
	return ""
}

func (x *OrderUpdateReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OrderUpdateReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *OrderUpdateReq) GetShipmentNo() string {
	if x != nil {
		return x.ShipmentNo
	}
	return ""
}

func (x *OrderUpdateReq) GetExpressName() string {
	if x != nil {
		return x.ExpressName
	}
	return ""
}

func (x *OrderUpdateReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type OrderUpdateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderUpdateResp) Reset() {
	*x = OrderUpdateResp{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderUpdateResp) ProtoMessage() {}

func (x *OrderUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderUpdateResp.ProtoReflect.Descriptor instead.
func (*OrderUpdateResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *OrderUpdateResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OrderUpdateResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type OrderListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListReq) Reset() {
	*x = OrderListReq{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListReq) ProtoMessage() {}

func (x *OrderListReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListReq.ProtoReflect.Descriptor instead.
func (*OrderListReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *OrderListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *OrderListReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type OrderListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Order               `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Code          int64                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListResp) Reset() {
	*x = OrderListResp{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListResp) ProtoMessage() {}

func (x *OrderListResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListResp.ProtoReflect.Descriptor instead.
func (*OrderListResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *OrderListResp) GetList() []*Order {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *OrderListResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OrderListResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Order struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderNo        string                 `protobuf:"bytes,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	UserID         uint64                 `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	OrderStatus    int64                  `protobuf:"varint,4,opt,name=orderStatus,proto3" json:"orderStatus,omitempty"`
	PaymentStatus  int64                  `protobuf:"varint,5,opt,name=paymentStatus,proto3" json:"paymentStatus,omitempty"`
	TotalAmount    int64                  `protobuf:"varint,6,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	PaidAmount     int64                  `protobuf:"varint,7,opt,name=paidAmount,proto3" json:"paidAmount,omitempty"`
	ConsigneeName  string                 `protobuf:"bytes,8,opt,name=consigneeName,proto3" json:"consigneeName,omitempty"`
	ConsigneePhone string                 `protobuf:"bytes,9,opt,name=consigneePhone,proto3" json:"consigneePhone,omitempty"`
	Address        string                 `protobuf:"bytes,10,opt,name=address,proto3" json:"address,omitempty"`
	Remark         string                 `protobuf:"bytes,11,opt,name=remark,proto3" json:"remark,omitempty"`
	ShipmentNo     string                 `protobuf:"bytes,12,opt,name=shipmentNo,proto3" json:"shipmentNo,omitempty"`
	ExpressName    string                 `protobuf:"bytes,13,opt,name=expressName,proto3" json:"expressName,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *Order) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *Order) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *Order) GetOrderStatus() int64 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *Order) GetPaymentStatus() int64 {
	if x != nil {
		return x.PaymentStatus
	}
	return 0
}

func (x *Order) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Order) GetPaidAmount() int64 {
	if x != nil {
		return x.PaidAmount
	}
	return 0
}

func (x *Order) GetConsigneeName() string {
	if x != nil {
		return x.ConsigneeName
	}
	return ""
}

func (x *Order) GetConsigneePhone() string {
	if x != nil {
		return x.ConsigneePhone
	}
	return ""
}

func (x *Order) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Order) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *Order) GetShipmentNo() string {
	if x != nil {
		return x.ShipmentNo
	}
	return ""
}

func (x *Order) GetExpressName() string {
	if x != nil {
		return x.ExpressName
	}
	return ""
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x06stream\"\x8e\x03\n" +
	"\x0eOrderCreateReq\x12\x18\n" +
	"\aorderNo\x18\x01 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\x04R\x06userID\x12 \n" +
	"\vorderStatus\x18\x04 \x01(\x03R\vorderStatus\x12$\n" +
	"\rpaymentStatus\x18\x05 \x01(\x03R\rpaymentStatus\x12 \n" +
	"\vtotalAmount\x18\x06 \x01(\x03R\vtotalAmount\x12\x1e\n" +
	"\n" +
	"paidAmount\x18\a \x01(\x03R\n" +
	"paidAmount\x12$\n" +
	"\rconsigneeName\x18\b \x01(\tR\rconsigneeName\x12&\n" +
	"\x0econsigneePhone\x18\t \x01(\tR\x0econsigneePhone\x12\x18\n" +
	"\aaddress\x18\n" +
	" \x01(\tR\aaddress\x12\x16\n" +
	"\x06remark\x18\v \x01(\tR\x06remark\x12\x1e\n" +
	"\n" +
	"shipmentNo\x18\f \x01(\tR\n" +
	"shipmentNo\x12 \n" +
	"\vexpressName\x18\r \x01(\tR\vexpressName\"7\n" +
	"\x0fOrderCreateResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\x1d\n" +
	"\vOrderDelReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"4\n" +
	"\fOrderDelResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\x9e\x03\n" +
	"\x0eOrderUpdateReq\x12\x18\n" +
	"\aorderNo\x18\x01 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\x04R\x06userID\x12 \n" +
	"\vorderStatus\x18\x04 \x01(\x03R\vorderStatus\x12$\n" +
	"\rpaymentStatus\x18\x05 \x01(\x03R\rpaymentStatus\x12 \n" +
	"\vtotalAmount\x18\x06 \x01(\x03R\vtotalAmount\x12\x1e\n" +
	"\n" +
	"paidAmount\x18\a \x01(\x03R\n" +
	"paidAmount\x12$\n" +
	"\rconsigneeName\x18\b \x01(\tR\rconsigneeName\x12&\n" +
	"\x0econsigneePhone\x18\t \x01(\tR\x0econsigneePhone\x12\x18\n" +
	"\aaddress\x18\n" +
	" \x01(\tR\aaddress\x12\x16\n" +
	"\x06remark\x18\v \x01(\tR\x06remark\x12\x1e\n" +
	"\n" +
	"shipmentNo\x18\f \x01(\tR\n" +
	"shipmentNo\x12 \n" +
	"\vexpressName\x18\r \x01(\tR\vexpressName\x12\x0e\n" +
	"\x02id\x18\x0e \x01(\x03R\x02id\"7\n" +
	"\x0fOrderUpdateResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"6\n" +
	"\fOrderListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"X\n" +
	"\rOrderListResp\x12!\n" +
	"\x04list\x18\x01 \x03(\v2\r.stream.OrderR\x04list\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\"\x85\x03\n" +
	"\x05Order\x12\x18\n" +
	"\aorderNo\x18\x01 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\x04R\x06userID\x12 \n" +
	"\vorderStatus\x18\x04 \x01(\x03R\vorderStatus\x12$\n" +
	"\rpaymentStatus\x18\x05 \x01(\x03R\rpaymentStatus\x12 \n" +
	"\vtotalAmount\x18\x06 \x01(\x03R\vtotalAmount\x12\x1e\n" +
	"\n" +
	"paidAmount\x18\a \x01(\x03R\n" +
	"paidAmount\x12$\n" +
	"\rconsigneeName\x18\b \x01(\tR\rconsigneeName\x12&\n" +
	"\x0econsigneePhone\x18\t \x01(\tR\x0econsigneePhone\x12\x18\n" +
	"\aaddress\x18\n" +
	" \x01(\tR\aaddress\x12\x16\n" +
	"\x06remark\x18\v \x01(\tR\x06remark\x12\x1e\n" +
	"\n" +
	"shipmentNo\x18\f \x01(\tR\n" +
	"shipmentNo\x12 \n" +
	"\vexpressName\x18\r \x01(\tR\vexpressName2\x80\x02\n" +
	"\rStreamGreeter\x12>\n" +
	"\vOrderCreate\x12\x16.stream.OrderCreateReq\x1a\x17.stream.OrderCreateResp\x125\n" +
	"\bOrderDel\x12\x13.stream.OrderDelReq\x1a\x14.stream.OrderDelResp\x12>\n" +
	"\vOrderUpdate\x12\x16.stream.OrderUpdateReq\x1a\x17.stream.OrderUpdateResp\x128\n" +
	"\tOrderList\x12\x14.stream.OrderListReq\x1a\x15.stream.OrderListRespB\x04Z\x02./b\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_order_proto_goTypes = []any{
	(*OrderCreateReq)(nil),  // 0: stream.OrderCreateReq
	(*OrderCreateResp)(nil), // 1: stream.OrderCreateResp
	(*OrderDelReq)(nil),     // 2: stream.OrderDelReq
	(*OrderDelResp)(nil),    // 3: stream.OrderDelResp
	(*OrderUpdateReq)(nil),  // 4: stream.OrderUpdateReq
	(*OrderUpdateResp)(nil), // 5: stream.OrderUpdateResp
	(*OrderListReq)(nil),    // 6: stream.OrderListReq
	(*OrderListResp)(nil),   // 7: stream.OrderListResp
	(*Order)(nil),           // 8: stream.Order
}
var file_order_proto_depIdxs = []int32{
	8, // 0: stream.OrderListResp.list:type_name -> stream.Order
	0, // 1: stream.StreamGreeter.OrderCreate:input_type -> stream.OrderCreateReq
	2, // 2: stream.StreamGreeter.OrderDel:input_type -> stream.OrderDelReq
	4, // 3: stream.StreamGreeter.OrderUpdate:input_type -> stream.OrderUpdateReq
	6, // 4: stream.StreamGreeter.OrderList:input_type -> stream.OrderListReq
	1, // 5: stream.StreamGreeter.OrderCreate:output_type -> stream.OrderCreateResp
	3, // 6: stream.StreamGreeter.OrderDel:output_type -> stream.OrderDelResp
	5, // 7: stream.StreamGreeter.OrderUpdate:output_type -> stream.OrderUpdateResp
	7, // 8: stream.StreamGreeter.OrderList:output_type -> stream.OrderListResp
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
