// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: Position.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PosCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Company       string                 `protobuf:"bytes,2,opt,name=company,proto3" json:"company,omitempty"`
	Salary        string                 `protobuf:"bytes,3,opt,name=salary,proto3" json:"salary,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Requirements  string                 `protobuf:"bytes,6,opt,name=requirements,proto3" json:"requirements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PosCreateReq) Reset() {
	*x = PosCreateReq{}
	mi := &file_Position_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PosCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PosCreateReq) ProtoMessage() {}

func (x *PosCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_Position_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PosCreateReq.ProtoReflect.Descriptor instead.
func (*PosCreateReq) Descriptor() ([]byte, []int) {
	return file_Position_proto_rawDescGZIP(), []int{0}
}

func (x *PosCreateReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PosCreateReq) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *PosCreateReq) GetSalary() string {
	if x != nil {
		return x.Salary
	}
	return ""
}

func (x *PosCreateReq) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *PosCreateReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PosCreateReq) GetRequirements() string {
	if x != nil {
		return x.Requirements
	}
	return ""
}

type PosCreateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PosCreateResp) Reset() {
	*x = PosCreateResp{}
	mi := &file_Position_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PosCreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PosCreateResp) ProtoMessage() {}

func (x *PosCreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_Position_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PosCreateResp.ProtoReflect.Descriptor instead.
func (*PosCreateResp) Descriptor() ([]byte, []int) {
	return file_Position_proto_rawDescGZIP(), []int{1}
}

func (x *PosCreateResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PosCreateResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type PosDelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PosDelReq) Reset() {
	*x = PosDelReq{}
	mi := &file_Position_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PosDelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PosDelReq) ProtoMessage() {}

func (x *PosDelReq) ProtoReflect() protoreflect.Message {
	mi := &file_Position_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PosDelReq.ProtoReflect.Descriptor instead.
func (*PosDelReq) Descriptor() ([]byte, []int) {
	return file_Position_proto_rawDescGZIP(), []int{2}
}

func (x *PosDelReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PosDelResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PosDelResp) Reset() {
	*x = PosDelResp{}
	mi := &file_Position_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PosDelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PosDelResp) ProtoMessage() {}

func (x *PosDelResp) ProtoReflect() protoreflect.Message {
	mi := &file_Position_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PosDelResp.ProtoReflect.Descriptor instead.
func (*PosDelResp) Descriptor() ([]byte, []int) {
	return file_Position_proto_rawDescGZIP(), []int{3}
}

func (x *PosDelResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PosDelResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type PosUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Company       string                 `protobuf:"bytes,2,opt,name=company,proto3" json:"company,omitempty"`
	Salary        string                 `protobuf:"bytes,3,opt,name=salary,proto3" json:"salary,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Requirements  string                 `protobuf:"bytes,6,opt,name=requirements,proto3" json:"requirements,omitempty"`
	Id            int64                  `protobuf:"varint,7,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PosUpdateReq) Reset() {
	*x = PosUpdateReq{}
	mi := &file_Position_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PosUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PosUpdateReq) ProtoMessage() {}

func (x *PosUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_Position_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PosUpdateReq.ProtoReflect.Descriptor instead.
func (*PosUpdateReq) Descriptor() ([]byte, []int) {
	return file_Position_proto_rawDescGZIP(), []int{4}
}

func (x *PosUpdateReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PosUpdateReq) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *PosUpdateReq) GetSalary() string {
	if x != nil {
		return x.Salary
	}
	return ""
}

func (x *PosUpdateReq) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *PosUpdateReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PosUpdateReq) GetRequirements() string {
	if x != nil {
		return x.Requirements
	}
	return ""
}

func (x *PosUpdateReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PosUpdateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PosUpdateResp) Reset() {
	*x = PosUpdateResp{}
	mi := &file_Position_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PosUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PosUpdateResp) ProtoMessage() {}

func (x *PosUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_Position_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PosUpdateResp.ProtoReflect.Descriptor instead.
func (*PosUpdateResp) Descriptor() ([]byte, []int) {
	return file_Position_proto_rawDescGZIP(), []int{5}
}

func (x *PosUpdateResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PosUpdateResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type PosListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PosListReq) Reset() {
	*x = PosListReq{}
	mi := &file_Position_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PosListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PosListReq) ProtoMessage() {}

func (x *PosListReq) ProtoReflect() protoreflect.Message {
	mi := &file_Position_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PosListReq.ProtoReflect.Descriptor instead.
func (*PosListReq) Descriptor() ([]byte, []int) {
	return file_Position_proto_rawDescGZIP(), []int{6}
}

func (x *PosListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PosListReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PosListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Position            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Code          int64                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PosListResp) Reset() {
	*x = PosListResp{}
	mi := &file_Position_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PosListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PosListResp) ProtoMessage() {}

func (x *PosListResp) ProtoReflect() protoreflect.Message {
	mi := &file_Position_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PosListResp.ProtoReflect.Descriptor instead.
func (*PosListResp) Descriptor() ([]byte, []int) {
	return file_Position_proto_rawDescGZIP(), []int{7}
}

func (x *PosListResp) GetList() []*Position {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *PosListResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PosListResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Company       string                 `protobuf:"bytes,3,opt,name=company,proto3" json:"company,omitempty"`
	Salary        string                 `protobuf:"bytes,4,opt,name=salary,proto3" json:"salary,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Requirements  string                 `protobuf:"bytes,7,opt,name=requirements,proto3" json:"requirements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_Position_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_Position_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_Position_proto_rawDescGZIP(), []int{8}
}

func (x *Position) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Position) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Position) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *Position) GetSalary() string {
	if x != nil {
		return x.Salary
	}
	return ""
}

func (x *Position) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Position) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Position) GetRequirements() string {
	if x != nil {
		return x.Requirements
	}
	return ""
}

var File_Position_proto protoreflect.FileDescriptor

const file_Position_proto_rawDesc = "" +
	"\n" +
	"\x0ePosition.proto\x12\x06stream\"\xb8\x01\n" +
	"\fPosCreateReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acompany\x18\x02 \x01(\tR\acompany\x12\x16\n" +
	"\x06salary\x18\x03 \x01(\tR\x06salary\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\"\n" +
	"\frequirements\x18\x06 \x01(\tR\frequirements\"5\n" +
	"\rPosCreateResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\x1b\n" +
	"\tPosDelReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"2\n" +
	"\n" +
	"PosDelResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\xc8\x01\n" +
	"\fPosUpdateReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acompany\x18\x02 \x01(\tR\acompany\x12\x16\n" +
	"\x06salary\x18\x03 \x01(\tR\x06salary\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\"\n" +
	"\frequirements\x18\x06 \x01(\tR\frequirements\x12\x0e\n" +
	"\x02id\x18\a \x01(\x03R\x02id\"5\n" +
	"\rPosUpdateResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"4\n" +
	"\n" +
	"PosListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"Y\n" +
	"\vPosListResp\x12$\n" +
	"\x04list\x18\x01 \x03(\v2\x10.stream.PositionR\x04list\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\"\xc4\x01\n" +
	"\bPosition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acompany\x18\x03 \x01(\tR\acompany\x12\x16\n" +
	"\x06salary\x18\x04 \x01(\tR\x06salary\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\"\n" +
	"\frequirements\x18\a \x01(\tR\frequirements2\xe8\x01\n" +
	"\rStreamGreeter\x128\n" +
	"\tPosCreate\x12\x14.stream.PosCreateReq\x1a\x15.stream.PosCreateResp\x12/\n" +
	"\x06PosDel\x12\x11.stream.PosDelReq\x1a\x12.stream.PosDelResp\x128\n" +
	"\tPosUpdate\x12\x14.stream.PosUpdateReq\x1a\x15.stream.PosUpdateResp\x122\n" +
	"\aPosList\x12\x12.stream.PosListReq\x1a\x13.stream.PosListRespB\x04Z\x02./b\x06proto3"

var (
	file_Position_proto_rawDescOnce sync.Once
	file_Position_proto_rawDescData []byte
)

func file_Position_proto_rawDescGZIP() []byte {
	file_Position_proto_rawDescOnce.Do(func() {
		file_Position_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Position_proto_rawDesc), len(file_Position_proto_rawDesc)))
	})
	return file_Position_proto_rawDescData
}

var file_Position_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_Position_proto_goTypes = []any{
	(*PosCreateReq)(nil),  // 0: stream.PosCreateReq
	(*PosCreateResp)(nil), // 1: stream.PosCreateResp
	(*PosDelReq)(nil),     // 2: stream.PosDelReq
	(*PosDelResp)(nil),    // 3: stream.PosDelResp
	(*PosUpdateReq)(nil),  // 4: stream.PosUpdateReq
	(*PosUpdateResp)(nil), // 5: stream.PosUpdateResp
	(*PosListReq)(nil),    // 6: stream.PosListReq
	(*PosListResp)(nil),   // 7: stream.PosListResp
	(*Position)(nil),      // 8: stream.Position
}
var file_Position_proto_depIdxs = []int32{
	8, // 0: stream.PosListResp.list:type_name -> stream.Position
	0, // 1: stream.StreamGreeter.PosCreate:input_type -> stream.PosCreateReq
	2, // 2: stream.StreamGreeter.PosDel:input_type -> stream.PosDelReq
	4, // 3: stream.StreamGreeter.PosUpdate:input_type -> stream.PosUpdateReq
	6, // 4: stream.StreamGreeter.PosList:input_type -> stream.PosListReq
	1, // 5: stream.StreamGreeter.PosCreate:output_type -> stream.PosCreateResp
	3, // 6: stream.StreamGreeter.PosDel:output_type -> stream.PosDelResp
	5, // 7: stream.StreamGreeter.PosUpdate:output_type -> stream.PosUpdateResp
	7, // 8: stream.StreamGreeter.PosList:output_type -> stream.PosListResp
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Position_proto_init() }
func file_Position_proto_init() {
	if File_Position_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Position_proto_rawDesc), len(file_Position_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Position_proto_goTypes,
		DependencyIndexes: file_Position_proto_depIdxs,
		MessageInfos:      file_Position_proto_msgTypes,
	}.Build()
	File_Position_proto = out.File
	file_Position_proto_goTypes = nil
	file_Position_proto_depIdxs = nil
}
