// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.4
// source: Position.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StreamGreeter_PosCreate_FullMethodName = "/stream.StreamGreeter/PosCreate"
	StreamGreeter_PosDel_FullMethodName    = "/stream.StreamGreeter/PosDel"
	StreamGreeter_PosUpdate_FullMethodName = "/stream.StreamGreeter/PosUpdate"
	StreamGreeter_PosList_FullMethodName   = "/stream.StreamGreeter/PosList"
)

// StreamGreeterClient is the client API for StreamGreeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamGreeterClient interface {
	PosCreate(ctx context.Context, in *PosCreateReq, opts ...grpc.CallOption) (*PosCreateResp, error)
	PosDel(ctx context.Context, in *PosDelReq, opts ...grpc.CallOption) (*PosDelResp, error)
	PosUpdate(ctx context.Context, in *PosUpdateReq, opts ...grpc.CallOption) (*PosUpdateResp, error)
	PosList(ctx context.Context, in *PosListReq, opts ...grpc.CallOption) (*PosListResp, error)
}

type streamGreeterClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamGreeterClient(cc grpc.ClientConnInterface) StreamGreeterClient {
	return &streamGreeterClient{cc}
}

func (c *streamGreeterClient) PosCreate(ctx context.Context, in *PosCreateReq, opts ...grpc.CallOption) (*PosCreateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PosCreateResp)
	err := c.cc.Invoke(ctx, StreamGreeter_PosCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamGreeterClient) PosDel(ctx context.Context, in *PosDelReq, opts ...grpc.CallOption) (*PosDelResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PosDelResp)
	err := c.cc.Invoke(ctx, StreamGreeter_PosDel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamGreeterClient) PosUpdate(ctx context.Context, in *PosUpdateReq, opts ...grpc.CallOption) (*PosUpdateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PosUpdateResp)
	err := c.cc.Invoke(ctx, StreamGreeter_PosUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamGreeterClient) PosList(ctx context.Context, in *PosListReq, opts ...grpc.CallOption) (*PosListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PosListResp)
	err := c.cc.Invoke(ctx, StreamGreeter_PosList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamGreeterServer is the server API for StreamGreeter service.
// All implementations must embed UnimplementedStreamGreeterServer
// for forward compatibility.
type StreamGreeterServer interface {
	PosCreate(context.Context, *PosCreateReq) (*PosCreateResp, error)
	PosDel(context.Context, *PosDelReq) (*PosDelResp, error)
	PosUpdate(context.Context, *PosUpdateReq) (*PosUpdateResp, error)
	PosList(context.Context, *PosListReq) (*PosListResp, error)
	mustEmbedUnimplementedStreamGreeterServer()
}

// UnimplementedStreamGreeterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamGreeterServer struct{}

func (UnimplementedStreamGreeterServer) PosCreate(context.Context, *PosCreateReq) (*PosCreateResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PosCreate not implemented")
}
func (UnimplementedStreamGreeterServer) PosDel(context.Context, *PosDelReq) (*PosDelResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PosDel not implemented")
}
func (UnimplementedStreamGreeterServer) PosUpdate(context.Context, *PosUpdateReq) (*PosUpdateResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PosUpdate not implemented")
}
func (UnimplementedStreamGreeterServer) PosList(context.Context, *PosListReq) (*PosListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PosList not implemented")
}
func (UnimplementedStreamGreeterServer) mustEmbedUnimplementedStreamGreeterServer() {}
func (UnimplementedStreamGreeterServer) testEmbeddedByValue()                       {}

// UnsafeStreamGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamGreeterServer will
// result in compilation errors.
type UnsafeStreamGreeterServer interface {
	mustEmbedUnimplementedStreamGreeterServer()
}

func RegisterStreamGreeterServer(s grpc.ServiceRegistrar, srv StreamGreeterServer) {
	// If the following call panics, it indicates UnimplementedStreamGreeterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StreamGreeter_ServiceDesc, srv)
}

func _StreamGreeter_PosCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PosCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamGreeterServer).PosCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamGreeter_PosCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamGreeterServer).PosCreate(ctx, req.(*PosCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamGreeter_PosDel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PosDelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamGreeterServer).PosDel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamGreeter_PosDel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamGreeterServer).PosDel(ctx, req.(*PosDelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamGreeter_PosUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PosUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamGreeterServer).PosUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamGreeter_PosUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamGreeterServer).PosUpdate(ctx, req.(*PosUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamGreeter_PosList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PosListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamGreeterServer).PosList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamGreeter_PosList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamGreeterServer).PosList(ctx, req.(*PosListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// StreamGreeter_ServiceDesc is the grpc.ServiceDesc for StreamGreeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamGreeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stream.StreamGreeter",
	HandlerType: (*StreamGreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PosCreate",
			Handler:    _StreamGreeter_PosCreate_Handler,
		},
		{
			MethodName: "PosDel",
			Handler:    _StreamGreeter_PosDel_Handler,
		},
		{
			MethodName: "PosUpdate",
			Handler:    _StreamGreeter_PosUpdate_Handler,
		},
		{
			MethodName: "PosList",
			Handler:    _StreamGreeter_PosList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Position.proto",
}
